// SPDX-License-Identifier: MIT
//
// Eustress MCP URI scheme — `eustress://<kind>/<...>` addressable
// resources. URIs here are intentionally 1:1 with Workshop's `@mention`
// canonical paths so the two systems share a single mental model:
// anything you can @-mention in Studio, you can pin as an MCP resource
// in an external editor.
//
// URI shape
//   eustress://<kind>/<space>/<...path>
//
// Kinds (v1):
//   space         folder-like; Space overview
//   script        a SoulScript/Rune/Luau folder — source + summary + diagnostics
//   entity        a folder-based entity, identified by its `_instance.toml`
//   file          any text file under a Space (markdown, toml, rune raw)
//   conversation  a Workshop session archive (no space in URI)
//   brief         an ideation_brief.toml (no space in URI — looked up across Spaces)
//
// `entity`/`file`/`script` always carry the space as the first path
// segment so two Spaces with same-named things don't collide; Workshop
// `@mention` canonical paths have the identical shape.

export type EustressUriKind =
  | 'space'
  | 'script'
  | 'entity'
  | 'file'
  | 'conversation'
  | 'brief';

export type EustressUri = {
  kind: EustressUriKind;
  /** Space name for space-qualified kinds (`space`, `script`, `entity`, `file`). */
  space?: string;
  /** Rest of the URI path after `<kind>/<space?>/`. Empty string if none. */
  relPath: string;
  /** Original URI string, preserved for echo in responses. */
  raw: string;
};

const SCHEME = 'eustress://';

/**
 * Parse `eustress://<kind>/...` → a structured [EustressUri]. Returns
 * `null` on malformed input so callers can emit a clean MCP error.
 */
export function parseUri(raw: string): EustressUri | null {
  if (!raw.startsWith(SCHEME)) return null;
  const body = raw.slice(SCHEME.length);
  const slash = body.indexOf('/');
  const kind = (slash >= 0 ? body.slice(0, slash) : body) as EustressUriKind;
  const rest = slash >= 0 ? body.slice(slash + 1) : '';

  if (!isKind(kind)) return null;

  // `conversation` + `brief` aren't space-qualified — the whole rest
  // is the identifier.
  if (kind === 'conversation' || kind === 'brief') {
    return { kind, relPath: rest, raw };
  }

  // Everything else takes a space segment first.
  const spaceSlash = rest.indexOf('/');
  const space = spaceSlash >= 0 ? rest.slice(0, spaceSlash) : rest;
  const relPath = spaceSlash >= 0 ? rest.slice(spaceSlash + 1) : '';
  if (!space) return null;
  return { kind, space, relPath, raw };
}

/**
 * Construct an `eustress://` URI. `relPath` is joined with `/`;
 * individual segments aren't re-encoded — callers should pass already
 * filesystem-safe names (Workshop's scripts + entities always are).
 */
export function buildUri(parts: {
  kind: EustressUriKind;
  space?: string;
  relPath?: string;
}): string {
  const { kind, space, relPath } = parts;
  if (kind === 'conversation' || kind === 'brief') {
    return `${SCHEME}${kind}/${relPath ?? ''}`;
  }
  const tail = relPath ? `/${relPath}` : '';
  return `${SCHEME}${kind}/${space}${tail}`;
}

/**
 * URI templates advertised via `resources/templates/list`. Clients use
 * these to construct URIs for resources they discover out-of-band
 * (e.g. "I see there's a script at `Space1/SoulService/foo` — give me
 * `eustress://script/Space1/SoulService/foo`"). `{+path}` is the
 * RFC 6570 "reserved expansion" form that preserves slashes.
 */
export const URI_TEMPLATES: Array<{
  uriTemplate: string;
  name: string;
  description: string;
  mimeType?: string;
}> = [
  {
    uriTemplate: 'eustress://space/{space}',
    name: 'Space',
    description: 'A Space in the current Universe. The resource body is an overview of its services + top-level scripts/entities.',
    mimeType: 'text/markdown',
  },
  {
    uriTemplate: 'eustress://script/{space}/{+path}',
    name: 'Script',
    description: 'A Rune/Luau script folder. Returns source + summary + (when available) live diagnostics in one bundled markdown document.',
    mimeType: 'text/markdown',
  },
  {
    uriTemplate: 'eustress://entity/{space}/{+path}',
    name: 'Entity',
    description: 'A folder-based entity identified by its `_instance.toml`. Returns the TOML plus a summary of children.',
    mimeType: 'text/markdown',
  },
  {
    uriTemplate: 'eustress://file/{space}/{+path}',
    name: 'File',
    description: 'Any text file under a Space — README, design notes, raw .rune or .toml. Binary files are rejected.',
    mimeType: 'text/plain',
  },
  {
    uriTemplate: 'eustress://conversation/{session_id}',
    name: 'Workshop conversation',
    description: 'A persisted Workshop chat session from `.eustress/knowledge/sessions/`.',
    mimeType: 'application/json',
  },
  {
    uriTemplate: 'eustress://brief/{product}',
    name: 'Ideation brief',
    description: 'An `ideation_brief.toml` generated by Workshop, addressed by product name.',
    mimeType: 'application/toml',
  },
];

function isKind(v: string): v is EustressUriKind {
  return v === 'space' || v === 'script' || v === 'entity'
      || v === 'file'  || v === 'conversation' || v === 'brief';
}
