// Material Sync - Real-time synchronization of BasePart properties to StandardMaterial
// Keeps visual appearance in sync with property changes

use bevy::prelude::*;
use bevy::asset::AssetEvent;
use bevy::light::{NotShadowCaster, TransmittedShadowReceiver};
use bevy::math::Affine2;
use crate::classes::{BasePart, Material as EustressMaterial, Part, PartType};
use crate::spawn::MeshSource;

mod planar_uv;

/// World size, in metres, that one material tile covers. The bundled library
/// (`common/assets/materials/textures/`, generated by `crates/texture-gen`) is
/// drawn at this scale: bricks come out brick-sized, boards board-sized.
const TILE_WORLD_SIZE: f32 = 4.0;

/// Copies of the flat primitives sized to the parts that draw them
/// ([`planar_uv::sized_copy`]).
///
/// A primitive's mesh is shared by every part of its shape, and one
/// `uv_transform` per part can scale a texture right for only one pair of
/// faces: on a small, long brick part the end faces took the long faces'
/// scale. A textured block, wedge or corner wedge is drawn from a copy whose
/// UVs are laid out in metres instead, with an identity `uv_transform`, so
/// every face shows the texture at world scale. Parts of one size share a
/// copy, and parts of one look share one material whatever their size.
#[derive(Resource, Default)]
struct SizedPrimitives {
    /// (primitive, size in millimetres) → copy. Weak, so a copy no part
    /// draws any more is freed.
    copies: std::collections::HashMap<(AssetId<Mesh>, IVec3), AssetId<Mesh>>,
    /// Copy → the primitive it was made from, and its key.
    sources: std::collections::HashMap<AssetId<Mesh>, (Handle<Mesh>, IVec3)>,
    /// Whether a mesh is a flat primitive, from its asset path.
    flat: std::collections::HashMap<AssetId<Mesh>, bool>,
}

impl SizedPrimitives {
    /// The mesh a part's `Mesh3d` stands for: the primitive behind a copy,
    /// otherwise the mesh itself.
    fn primitive_of(&self, mesh: &Handle<Mesh>) -> Handle<Mesh> {
        self.sources.get(&mesh.id()).map_or_else(|| mesh.clone(), |(primitive, _)| primitive.clone())
    }

    fn is_flat(&mut self, asset_server: &AssetServer, id: AssetId<Mesh>) -> bool {
        *self.flat.entry(id).or_insert_with(|| is_flat_primitive(asset_server, id))
    }

    /// The copy of `primitive` for a part of `size`, made on first use.
    /// `None` while the primitive is still loading.
    fn copy_for(&mut self, meshes: &mut Assets<Mesh>, primitive: &Handle<Mesh>, size: Vec3) -> Option<Handle<Mesh>> {
        // To the millimetre: finer than any visible difference in texture
        // scale, and coarse enough that parts cut to one size share a copy.
        let key = (size.abs() * 1000.0).round().as_ivec3().max(IVec3::ONE);
        if let Some(&id) = self.copies.get(&(primitive.id(), key)) {
            if let Some(handle) = meshes.get_strong_handle(id) {
                return Some(handle);
            }
        }
        let copy = planar_uv::sized_copy(meshes.get(primitive)?, key.as_vec3() / 1000.0, TILE_WORLD_SIZE)?;
        let handle = meshes.add(copy);
        self.copies.insert((primitive.id(), key), handle.id());
        self.sources.insert(handle.id(), (primitive.clone(), key));
        Some(handle)
    }

    /// Drop what is known about a mesh that has been freed.
    fn forget(&mut self, id: AssetId<Mesh>) {
        self.flat.remove(&id);
        if let Some((primitive, key)) = self.sources.remove(&id) {
            if self.copies.get(&(primitive.id(), key)) == Some(&id) {
                self.copies.remove(&(primitive.id(), key));
            }
        }
    }
}

/// On a part drawn from a copy in [`SizedPrimitives`].
#[derive(Component)]
struct DrawnFromCopy(AssetId<Mesh>);

/// On a textured flat part whose primitive has not loaded yet. It is drawn
/// with a part-wide `uv_transform` until the primitive can be copied.
#[derive(Component)]
struct AwaitingPrimitive(AssetId<Mesh>);

/// Tracks the last-known size of the MaterialRegistry to detect when new materials load.
#[derive(Resource, Default)]
struct MaterialRegistryTracker {
    last_count: usize,
}

/// Meshes adjusted so library materials map onto them correctly
/// (see [`prepare_meshes_for_materials`]).
#[derive(Resource, Default)]
struct PreparedMeshes {
    /// Meshes a normal-mapped material was applied to that still need
    /// tangents, kept until their asset is resident.
    want_tangents: std::collections::HashSet<AssetId<Mesh>>,
}

/// Tracks which registry materials have already had their textures patched to Repeat.
/// Avoids re-scanning every material × 6 texture slots on every single frame.
#[derive(Resource, Default)]
struct PatchedTextureTracker {
    patched_materials: std::collections::HashSet<String>,
}

/// Plugin for syncing BasePart properties to StandardMaterial in real-time
pub struct MaterialSyncPlugin;

impl Plugin for MaterialSyncPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<MaterialRegistryTracker>()
            .init_resource::<PatchedTextureTracker>()
            .init_resource::<PreparedMeshes>()
            .init_resource::<SizedPrimitives>()
            .add_systems(Update, (
                reapply_materials_on_registry_change,
                set_material_textures_to_repeat,
                release_replaced_copies,
                sync_basepart_to_material,
                hydrate_used_material_textures,
                prepare_meshes_for_materials,
            ).chain());
    }
}

/// Ensure all material textures use Repeat address mode for proper tiling.
/// Bevy defaults to ClampToEdge, which causes visible seams at UV tile
/// boundaries on textured parts. This system runs once per texture when
/// the Image asset finishes loading.
fn set_material_textures_to_repeat(
    material_registry: Option<Res<crate::space::material_loader::MaterialRegistry>>,
    materials: Res<Assets<StandardMaterial>>,
    mut images: ResMut<Assets<Image>>,
    mut tracker: ResMut<PatchedTextureTracker>,
) {
    let Some(ref registry) = material_registry else { return };
    // Early out: if we've patched every known material, nothing to do.
    if tracker.patched_materials.len() >= registry.len() {
        return;
    }
    // Only iterate materials we haven't patched yet.
    for name in registry.names() {
        if tracker.patched_materials.contains(&name) {
            continue;
        }
        let Some(mat_handle) = registry.get(&name) else { continue };
        let Some(mat) = materials.get(&mat_handle) else { continue };
        // Process all texture slots on this material
        let texture_handles = [
            mat.base_color_texture.clone(),
            mat.normal_map_texture.clone(),
            mat.metallic_roughness_texture.clone(),
            mat.emissive_texture.clone(),
            mat.occlusion_texture.clone(),
            mat.depth_map.clone(),
        ];
        let mut all_patched = true;
        for opt_handle in texture_handles.into_iter().flatten() {
            // Read-only check first to avoid marking the image as changed
            let needs_update = if let Some(image) = images.get(&opt_handle) {
                match &image.sampler {
                    bevy::image::ImageSampler::Default => true,
                    bevy::image::ImageSampler::Descriptor(desc) => {
                        // Wrap AND filtering both have to be right. Testing only
                        // the address mode meant a texture that already tiled but
                        // sampled Nearest counted as done, so the filtering fix
                        // below could never reach it.
                        desc.address_mode_u != bevy::image::ImageAddressMode::Repeat
                            || desc.min_filter != bevy::image::ImageFilterMode::Linear
                            || desc.mipmap_filter != bevy::image::ImageFilterMode::Linear
                            || desc.anisotropy_clamp < 2
                    }
                }
            } else {
                // Not in `Assets<Image>`: either still loading, or loaded
                // `RENDER_WORLD`-only by `material_loader::load_image`, which
                // bakes this exact sampler in at load time. Either way there
                // is nothing to patch. Treating it as "unpatched, retry" made
                // this system rescan every material every frame, forever,
                // once textures stopped being CPU-resident.
                continue;
            };
            if needs_update {
                if let Some(mut image) = images.get_mut(&opt_handle) {
                    // Change ONLY the address modes; keep whatever filtering the
                    // asset arrived with.
                    //
                    // This used to spread `..Default::default()`, and Bevy's
                    // `ImageFilterMode` defaults to `Nearest` (`bevy_image`'s
                    // enum carries `#[default] Nearest`). So making a texture
                    // tile also silently set mag/min/mipmap to Nearest and
                    // `anisotropy_clamp: 1` — it fixed the wrap and destroyed the
                    // filtering in the same statement.
                    //
                    // On a large flat surface seen at a grazing angle that reads
                    // exactly like a broken texture: nearest MIPMAP filtering
                    // gives hard, unblended mip boundaries (an abrupt smeared
                    // band partway across the face), no anisotropy over-blurs
                    // everything past the first mip, and nearest magnification
                    // aliases the detail near the camera. The tiling itself was
                    // fine; the sampling was not.
                    let base = match &image.sampler {
                        bevy::image::ImageSampler::Descriptor(d) => d.clone(),
                        // Arrived unconfigured — Nearest by Bevy default, which
                        // is wrong for a tiled surface texture.
                        bevy::image::ImageSampler::Default => {
                            bevy::image::ImageSamplerDescriptor::linear()
                        }
                    };
                    image.sampler = bevy::image::ImageSampler::Descriptor(
                        bevy::image::ImageSamplerDescriptor {
                            address_mode_u: bevy::image::ImageAddressMode::Repeat,
                            address_mode_v: bevy::image::ImageAddressMode::Repeat,
                            address_mode_w: bevy::image::ImageAddressMode::Repeat,
                            // Anisotropy is the specific fix for ground/road
                            // surfaces: without it a tiled plane viewed edge-on
                            // collapses into a blur a short distance out. wgpu
                            // requires all three filters to be Linear when this
                            // is > 1, so they are forced together.
                            mag_filter: bevy::image::ImageFilterMode::Linear,
                            min_filter: bevy::image::ImageFilterMode::Linear,
                            mipmap_filter: bevy::image::ImageFilterMode::Linear,
                            anisotropy_clamp: 16,
                            ..base
                        }
                    );
                }
            }
        }
        if all_patched {
            tracker.patched_materials.insert(name);
        }
    }
}

/// When MaterialService finishes loading (registry grows OR shrinks), mark
/// all BaseParts as changed so `sync_basepart_to_material` re-resolves them
/// against the current registry.
///
/// Detecting size CHANGES (`!=`) rather than only GROWTH (`>`) is critical
/// after a Space switch: if the new Space has fewer materials than the
/// previous one, `current_count` is smaller than `last_count` and a
/// growth-only check never fires — leaving every Part in the new Space
/// rendered with the default fallback material. The user's "materials
/// don't load when switching Spaces" report traced to exactly this case.
/// Also reset `PatchedTextureTracker` so the texture-repeat patcher
/// re-runs against the new registry's materials.
fn reapply_materials_on_registry_change(
    material_registry: Option<Res<crate::space::material_loader::MaterialRegistry>>,
    mut tracker: ResMut<MaterialRegistryTracker>,
    mut patched: ResMut<PatchedTextureTracker>,
    mut base_parts: Query<&mut BasePart>,
    // Gate: while a Space load is still streaming, the MaterialRegistry grows on
    // EVERY spawn batch, so touching ALL parts on each incremental change was
    // O(N²) across the load (re-resolving every already-spawned part, per
    // batch). On Vehicle Simulator (387K parts) that dominated the frame and
    // made frame time GROW as parts accumulated (29s → 39s and climbing).
    // Freshly-spawned parts already resolve their material via Changed<BasePart>
    // at spawn, so the catch-all reapply only needs to run ONCE — after the load
    // settles (`LoadInProgress.active` flips false). Collapses O(N²) → O(N).
    load: Option<Res<crate::space::file_loader::LoadInProgress>>,
) {
    if load.map_or(false, |l| l.active) {
        return;
    }
    let Some(ref registry) = material_registry else { return };
    let current_count = registry.len();
    if current_count != tracker.last_count {
        info!("🎨 MaterialRegistry changed ({} → {}), re-applying materials to all parts",
              tracker.last_count, current_count);
        tracker.last_count = current_count;
        patched.patched_materials.clear();
        // Touch all BaseParts so Changed<BasePart> triggers sync
        for mut bp in base_parts.iter_mut() {
            bp.set_changed();
        }
    }
}

/// System to sync BasePart properties (Color, Material, Reflectance, Transparency) to StandardMaterial
fn sync_basepart_to_material(
    mut commands: Commands,
    mut materials: ResMut<Assets<StandardMaterial>>,
    // Needed so the registry can attach a library material's texture maps on
    // first use, BEFORE `resolve_part_material` snapshots the template.
    asset_server: Res<AssetServer>,
    // R2.1: ResMut (was Res) — `sync` now resolves SHARED, deduplicated material
    // handles via the registry's dedup cache instead of cloning a unique
    // material per entity. A unique handle per entity defeats Bevy's batching
    // (batch key = material bind group + mesh) → one draw call per entity, the
    // ~60K-entity scale wall. Sharing collapses identical-appearance parts into
    // a handful of batched/indirect draws.
    mut material_registry: Option<ResMut<crate::space::material_loader::MaterialRegistry>>,
    mut prepared: ResMut<PreparedMeshes>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut sized: ResMut<SizedPrimitives>,
    query: Query<(
        Entity,
        Ref<BasePart>,
        &Transform,
        // Required so we only sync entities that already have a material (a
        // guard, not used directly now that we insert a fresh shared handle).
        &MeshMaterial3d<StandardMaterial>,
        Option<&NotShadowCaster>,
        Option<&TransmittedShadowReceiver>,
        (Option<&Mesh3d>, Option<&MeshSource>, Option<&Part>),
        (Option<&DrawnFromCopy>, Option<&AwaitingPrimitive>),
    ), Or<(Changed<BasePart>, With<AwaitingPrimitive>)>>,
    // NOTE: Previously also triggered on Changed<Transform>, which caused
    // a full material clone + GPU allocation EVERY FRAME for every entity
    // whose transform changed (camera orbit, physics, animations, etc.).
    // UV transform is derived from BasePart.size, not Transform.scale,
    // so Changed<BasePart> is sufficient.
) {
    for (entity, basepart, transform, _material_handle, has_no_shadow, has_transmission, (mesh3d, mesh_source, part), (drawn_from_copy, awaiting)) in query.iter() {
        // Waiting for its primitive to load, with nothing else changed.
        if let Some(AwaitingPrimitive(primitive)) = awaiting {
            if !basepart.is_changed() && !meshes.contains(*primitive) {
                if !matches!(asset_server.get_load_state(*primitive), Some(bevy::asset::LoadState::Loading)) {
                    commands.entity(entity).remove::<AwaitingPrimitive>();
                }
                continue;
            }
        }
        let is_glass = matches!(basepart.material, EustressMaterial::Glass);
        // The mesh behind the part: the primitive when it is drawn from a copy.
        let primitive = mesh3d.map(|m| sized.primitive_of(&m.0));

        // ── R2.1: resolve a SHARED material handle (copy-on-write) ──
        // Replaces the former three branches (registry-clone ×2 + in-place
        // `get_mut`). `resolve_part_material` reproduces that exact tint math
        // (so visuals are unchanged — C2) but returns a deduplicated handle:
        // identical-appearance parts share ONE handle → Bevy batches them.
        // Editing one part re-resolves it to the handle matching its NEW look,
        // never mutating others (the deleted in-place `get_mut` was the classic
        // "edit one, change all" bug once handles are shared).
        // Gap 5 — respect embedded glTF materials. When the part opts in,
        // skip applying the single engine-derived StandardMaterial entirely
        // so the mesh keeps the material it loaded with (its own glTF
        // material). The shadow / transmission bookkeeping below still runs.
        if basepart.respect_gltf_materials {
            // fall through to shadow/transmission handling without touching
            // MeshMaterial3d; a copy's UVs are not the ones the mesh came with
            if let (Some(_), Some(primitive)) = (drawn_from_copy, primitive) {
                commands.entity(entity).insert(Mesh3d(primitive)).remove::<DrawnFromCopy>();
            }
        } else if let Some(ref mut registry) = material_registry {
            // Custom `.mat.toml` name first, then the preset enum name — the
            // (possibly textured) base material to clone+tint, if registered.
            let mat_name = if basepart.material_name.is_empty() {
                format!("{:?}", basepart.material)
            } else {
                basepart.material_name.clone()
            };
            let base_template = registry
                .get(&mat_name)
                .or_else(|| registry.get(basepart.material.as_str()));
            let resolve = |registry: &mut crate::space::material_loader::MaterialRegistry,
                           materials: &mut Assets<StandardMaterial>,
                           uv: Affine2| {
                registry.resolve_part_material(
                    materials,
                    &asset_server,
                    &mat_name,
                    basepart.material,
                    base_template.clone(),
                    basepart.color,
                    basepart.transparency,
                    basepart.reflectance,
                    uv,
                )
            };
            let layout = uv_layout(mesh_source, part);
            let part_uv = compute_uv_transform(&basepart, Some(transform.scale), layout);
            // A flat primitive can be drawn from a copy sized to the part
            // (see `SizedPrimitives`), unless explicit tile counts are set.
            let sizable = primitive.as_ref().filter(|p| {
                layout == UvLayout::Planar
                    && basepart.texture_repeat == [1.0, 1.0]
                    && sized.is_flat(&asset_server, p.id())
            });
            // Resolving with the copy's identity transform also tells whether
            // the material has maps at all; without them the plain primitive
            // does, and the transform is ignored.
            let mut handle = resolve(&mut **registry, &mut *materials, if sizable.is_some() { Affine2::IDENTITY } else { part_uv });
            let mut draw = primitive.clone();
            let mut copy = None;
            let mut awaiting_now = None;
            if let Some(primitive) = sizable {
                if materials.get(&handle).is_some_and(has_maps) {
                    match sized.copy_for(&mut meshes, primitive, basepart.size) {
                        Some(sized_copy) => {
                            copy = Some(sized_copy.id());
                            draw = Some(sized_copy);
                        }
                        // Still loading: nothing is drawn until it arrives, so
                        // keep the shared material rather than resolving one
                        // per part size for a mesh no one can see yet.
                        None if !meshes.contains(primitive.id()) => {
                            awaiting_now = Some(primitive.id());
                        }
                        None => {
                            handle = resolve(&mut **registry, &mut *materials, part_uv);
                        }
                    }
                }
            }
            if let Some(mesh) = draw {
                // Copies carry tangents; Bevy applies a normal map only to a
                // mesh with them, so any other mesh gets them on demand.
                if copy.is_none() && materials.get(&handle).is_some_and(|m| m.normal_map_texture.is_some()) {
                    prepared.want_tangents.insert(mesh.id());
                }
                if mesh3d.map(|m| m.id()) != Some(mesh.id()) {
                    commands.entity(entity).insert(Mesh3d(mesh));
                }
            }
            match copy {
                Some(id) if drawn_from_copy.map(|d| d.0) != Some(id) => {
                    commands.entity(entity).insert(DrawnFromCopy(id));
                }
                None if drawn_from_copy.is_some() => {
                    commands.entity(entity).remove::<DrawnFromCopy>();
                }
                _ => {}
            }
            match awaiting_now {
                Some(id) => {
                    commands.entity(entity).insert(AwaitingPrimitive(id));
                }
                None if awaiting.is_some() => {
                    commands.entity(entity).remove::<AwaitingPrimitive>();
                }
                None => {}
            }
            commands.entity(entity).insert(MeshMaterial3d(handle));
        }
        // No registry resource yet (very early frames): leave the existing
        // handle; `reapply_materials_on_registry_change` re-runs sync once the
        // registry loads.

        // Shadow casting: respect the explicit `cast_shadow` property AND
        // the >= 50% transparency threshold. Either condition opts the
        // entity out of shadow cascades. At 50k+ anchored static parts the
        // shadow pass is the dominant render cost, so honouring the TOML
        // `cast_shadow = false` is a first-class perf knob, not a nice-to-have.
        let should_cast_shadow = basepart.cast_shadow && basepart.transparency < 0.5;
        if should_cast_shadow {
            if has_no_shadow.is_some() {
                commands.entity(entity).remove::<NotShadowCaster>();
            }
        } else {
            if has_no_shadow.is_none() {
                commands.entity(entity).insert(NotShadowCaster);
            }
        }

        // Glass with < 50% transparency gets TransmittedShadowReceiver for colored shadows
        let needs_transmission = is_glass && basepart.transparency < 0.5;
        if needs_transmission {
            if has_transmission.is_none() {
                commands.entity(entity).insert(TransmittedShadowReceiver);
            }
        } else {
            if has_transmission.is_some() {
                commands.entity(entity).remove::<TransmittedShadowReceiver>();
            }
        }
    }
}

/// Whether a material samples any texture, so its UVs matter.
fn has_maps(m: &StandardMaterial) -> bool {
    m.base_color_texture.is_some()
        || m.normal_map_texture.is_some()
        || m.metallic_roughness_texture.is_some()
        || m.occlusion_texture.is_some()
        || m.emissive_texture.is_some()
}

/// A part drawn from a sized copy whose mesh something else has since
/// replaced (a shape change, a mesh edit) resolves its material again: the
/// copy's identity `uv_transform` is wrong for any other mesh.
fn release_replaced_copies(
    mut commands: Commands,
    mut parts: Query<(Entity, &Mesh3d, &DrawnFromCopy, &mut BasePart), Changed<Mesh3d>>,
) {
    for (entity, mesh, copy, mut basepart) in &mut parts {
        if mesh.id() != copy.0 {
            commands.entity(entity).remove::<DrawnFromCopy>();
            basepart.set_changed();
        }
    }
}

/// How a part's mesh lays out its UVs, which decides how `uv_transform`
/// scales them to world size.
#[derive(Clone, Copy, Debug, PartialEq)]
enum UvLayout {
    /// Block, wedge, corner wedge: face-planar UVs in unscaled metres
    /// ([`planar_uv::planar_uv`]), U horizontal and V down each face.
    /// Textured ones are drawn from sized copies ([`SizedPrimitives`]); a
    /// `uv_transform` for this layout serves the rest: explicit
    /// `texture_repeat` and a primitive that has not loaded yet.
    Planar,
    /// Ball: equirectangular, U once around, V pole to pole.
    Sphere,
    /// Cylinder, cone and custom meshes: their own UVs.
    Authored,
}

fn layout_for_shape(shape: PartType) -> UvLayout {
    match shape {
        PartType::Block | PartType::Wedge | PartType::CornerWedge => UvLayout::Planar,
        PartType::Ball => UvLayout::Sphere,
        PartType::Cylinder | PartType::Cone => UvLayout::Authored,
    }
}

/// An engine primitive's shape from its mesh path (`parts/block.glb` and
/// friends); `None` for any other mesh.
fn primitive_shape(path: &str) -> Option<PartType> {
    let path = std::path::Path::new(path);
    let in_parts = path.parent().and_then(|d| d.file_name()).is_some_and(|d| d == "parts");
    if !in_parts {
        return None;
    }
    match path.file_name()?.to_str()? {
        "block.glb" => Some(PartType::Block),
        "wedge.glb" => Some(PartType::Wedge),
        "corner_wedge.glb" => Some(PartType::CornerWedge),
        "ball.glb" => Some(PartType::Ball),
        "cylinder.glb" => Some(PartType::Cylinder),
        "cone.glb" => Some(PartType::Cone),
        _ => None,
    }
}

/// The mesh path decides when there is one (a custom mesh keeps its own
/// UVs even though its `Part.shape` defaults to Block); otherwise the shape.
fn uv_layout(source: Option<&MeshSource>, part: Option<&Part>) -> UvLayout {
    let shape = match source {
        Some(s) => primitive_shape(&s.path),
        None => part.map(|p| p.shape),
    };
    shape.map_or(UvLayout::Authored, layout_for_shape)
}

/// Tiles per UV unit so one tile covers [`TILE_WORLD_SIZE`] metres.
///
/// One `uv_transform` serves every face of the part, so for planar meshes it
/// is sized for the part's broad faces: the top and bottom of anything flatter
/// than it is wide, otherwise the larger pair of sides (U along the long
/// horizontal, V down). Faces that share those axes are exact too; only the
/// narrow end and edge faces are approximate. Textured flat primitives are
/// drawn from sized copies instead ([`SizedPrimitives`]), exact on every face.
fn uv_scale_for_size(s: Vec3, layout: UvLayout) -> Affine2 {
    let scale = match layout {
        UvLayout::Planar => {
            if s.y < s.x.min(s.z) {
                Vec2::new(s.x, s.z)
            } else if s.z <= s.x {
                Vec2::new(s.x, s.y)
            } else {
                Vec2::new(s.z, s.y)
            }
        }
        UvLayout::Sphere => {
            let girth = std::f32::consts::PI * (s.x + s.z) * 0.5;
            let meridian = std::f32::consts::PI * (s.y + (s.x + s.z) * 0.5) * 0.25;
            Vec2::new(girth, meridian)
        }
        UvLayout::Authored => {
            let mut dims = [s.x, s.y, s.z];
            dims.sort_by(|a, b| b.partial_cmp(a).unwrap_or(std::cmp::Ordering::Equal));
            Vec2::new(dims[0], dims[1])
        }
    };
    Affine2::from_scale((scale / TILE_WORLD_SIZE).max(Vec2::splat(1e-3)))
}

/// Spawn-time UV transform, for `spawn_part_glb` to render the first frame at
/// the right texture density before `sync_basepart_to_material` sees the part.
pub fn compute_uv_transform_from_size(size: Vec3, shape: PartType) -> Affine2 {
    uv_scale_for_size(size.abs().max(Vec3::splat(1e-3)), layout_for_shape(shape))
}

/// A part's `uv_transform`: its world size scaled per [`uv_scale_for_size`].
///
/// `transform_scale`: for file-system-first parts `Transform.scale = size`;
/// for legacy parts it can differ from `BasePart.size` mid-drag, and passing
/// it keeps the UVs matched to what the GPU draws. When `None`,
/// `BasePart.size` alone is used.
///
/// `BasePart.texture_repeat` overrides all of this when set to anything but
/// `[1.0, 1.0]`: scripts and the asset pipeline can dial in exact tile counts
/// when they know the surface they are on.
fn compute_uv_transform(basepart: &BasePart, transform_scale: Option<Vec3>, layout: UvLayout) -> Affine2 {
    let [u_repeat, v_repeat] = basepart.texture_repeat;
    if u_repeat != 1.0 || v_repeat != 1.0 {
        return Affine2::from_scale(Vec2::new(u_repeat, v_repeat));
    }
    // Effective world-space size: if the caller provides the live
    // Transform.scale we multiply it element-wise with BasePart.size
    // so that mid-drag legacy parts (scale = size/baked) combined with
    // the baked mesh dimensions produce the correct visual size. For
    // file-system-first parts (unit mesh, scale = size) this is just
    // size * 1 = size. When no transform_scale is available, use
    // BasePart.size directly — correct for newly spawned parts whose
    // Transform hasn't been queried yet.
    let world_size = match transform_scale {
        Some(ts) => {
            // File-system-first: unit mesh × scale = world dims.
            // Legacy final: mesh baked at size, scale = ONE → size × 1 = size.
            // Legacy mid-drag: mesh baked at old_size, scale = size/old_size
            //   → old_size isn't in BasePart anymore (overwritten), but
            //   BasePart.size IS the target size the user is dragging to,
            //   so just use BasePart.size to keep UVs predictive of the
            //   final result rather than the transient mesh ratio.
            Vec3::new(
                basepart.size.x.abs().max(ts.x.abs()).max(1e-3),
                basepart.size.y.abs().max(ts.y.abs()).max(1e-3),
                basepart.size.z.abs().max(ts.z.abs()).max(1e-3),
            )
        }
        None => Vec3::new(
            basepart.size.x.abs().max(1e-3),
            basepart.size.y.abs().max(1e-3),
            basepart.size.z.abs().max(1e-3),
        ),
    };
    uv_scale_for_size(world_size, layout)
}

/// Attach a library material's texture maps the first time any Part uses it.
///
/// Materials are registered WITHOUT their maps (see
/// `material_loader::build_standard_material`); this is the other half. It
/// runs only for parts whose material handle was just added or changed, asks
/// the registry whether that handle is a library material, and hydrates it
/// once. A material nobody applies never loads a byte of texture.
fn hydrate_used_material_textures(
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    mut material_registry: Option<ResMut<crate::space::material_loader::MaterialRegistry>>,
    // `Changed` also covers the frame the handle is added; a separate `Added`
    // arm only doubled the per-entity tick checks of this every-frame scan.
    changed: Query<&MeshMaterial3d<StandardMaterial>, Changed<MeshMaterial3d<StandardMaterial>>>,
) {
    let Some(ref mut registry) = material_registry else { return };
    if changed.is_empty() {
        return;
    }
    // Dedupe per frame: many parts share one handle.
    let mut seen: std::collections::HashSet<bevy::asset::AssetId<StandardMaterial>> =
        std::collections::HashSet::new();
    for mat in &changed {
        if !seen.insert(mat.0.id()) {
            continue;
        }
        let Some(name) = registry.name_for_handle(&mat.0).map(|s| s.to_string()) else {
            continue; // a dedup-cache or preset material, not a library one
        };
        registry.hydrate_textures(&name, &asset_server, &mut materials);
    }
}

/// Make meshes take library materials correctly.
///
/// * **Planar UVs and outward winding on the flat primitives.** `block.glb`,
///   `wedge.glb` and `corner_wedge.glb` are unit meshes whose every face is
///   planar. Each face gets the object-space coordinates of its own plane as
///   UVs ([`planar_uv::planar_uv`]): one UV unit per unscaled metre, U to the
///   right and V down on side faces (textures stand upright on walls), U
///   along X and V along Z on top and bottom. The exported cross unwrap gave
///   each face a quarter of UV space with U running vertically on the sides,
///   and the corner wedge had no UVs at all. Triangles wound against their
///   normals are turned to face out ([`planar_uv::fix_winding`]); the wedges
///   used to be culled from outside.
/// * **Tangents.** Bevy applies a normal map only to a mesh with tangents,
///   and neither the primitives nor most imported meshes carry them. The flat
///   primitives get MikkTSpace tangents with their UVs; any other mesh gets
///   them the first time a normal-mapped material is applied to it
///   (`sync_basepart_to_material` queues it).
///
/// A primitive counts as prepared once it has tangents, so a mesh reloaded
/// from disk is prepared again and this system's own edits are not. Freed
/// meshes are dropped from [`SizedPrimitives`] here too.
fn prepare_meshes_for_materials(
    mut events: MessageReader<AssetEvent<Mesh>>,
    mut meshes: ResMut<Assets<Mesh>>,
    asset_server: Res<AssetServer>,
    mut prepared: ResMut<PreparedMeshes>,
    mut sized: ResMut<SizedPrimitives>,
) {
    let mut todo: std::collections::HashSet<AssetId<Mesh>> = std::collections::HashSet::new();
    for event in events.read() {
        let id = match event {
            AssetEvent::Added { id } | AssetEvent::Modified { id } => *id,
            AssetEvent::Removed { id } => {
                sized.forget(*id);
                continue;
            }
            _ => continue,
        };
        if is_flat_primitive(&asset_server, id) {
            todo.insert(id);
        }
    }
    if !prepared.want_tangents.is_empty() {
        let wanted: Vec<AssetId<Mesh>> = prepared.want_tangents.iter().copied().collect();
        for id in wanted {
            // Not resident: wait while it is still loading, otherwise drop it
            // (failed, removed, or render-world-only with no CPU copy to edit).
            if meshes.get(id).is_none()
                && matches!(asset_server.get_load_state(id), Some(bevy::asset::LoadState::Loading))
            {
                continue;
            }
            prepared.want_tangents.remove(&id);
            todo.insert(id);
        }
    }
    for id in todo {
        let Some(mesh) = meshes.get(id) else { continue };
        if mesh.attribute(Mesh::ATTRIBUTE_TANGENT).is_some() {
            continue;
        }
        let flat = is_flat_primitive(&asset_server, id);
        let has_uvs = mesh.attribute(Mesh::ATTRIBUTE_UV_0).is_some();
        if !flat && (!has_uvs || mesh.attribute(Mesh::ATTRIBUTE_NORMAL).is_none()) {
            continue;
        }
        let Some(mut mesh) = meshes.get_mut(id) else { continue };
        if flat {
            let turned = planar_uv::fix_winding(&mut mesh);
            if turned > 0 {
                info!("Turned {} inward triangles of {:?} to face out", turned, asset_server.get_path(id));
            }
            if let Some(uvs) = planar_uv::planar_face_uvs(&mesh, Vec3::ONE, 1.0) {
                mesh.insert_attribute(Mesh::ATTRIBUTE_UV_0, uvs);
            }
        }
        if let Err(e) = mesh.generate_tangents() {
            warn!("No tangents for mesh {:?}: {}", asset_server.get_path(id), e);
        }
    }
}

fn is_flat_primitive(asset_server: &AssetServer, id: AssetId<Mesh>) -> bool {
    asset_server.get_path(id).is_some_and(|p| {
        p.path()
            .to_str()
            .and_then(primitive_shape)
            .is_some_and(|s| layout_for_shape(s) == UvLayout::Planar)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn broad_faces_get_exact_density() {
        let tiles = |s: Vec3| uv_scale_for_size(s, UvLayout::Planar).matrix2;
        // A 20 x 1 x 12 floor: top shows 5 x 3 tiles.
        let m = tiles(Vec3::new(20.0, 1.0, 12.0));
        assert_eq!((m.x_axis.x, m.y_axis.y), (5.0, 3.0));
        // A wall along Z: its X faces are the broad ones, U along Z.
        let m = tiles(Vec3::new(0.5, 6.0, 10.0));
        assert_eq!((m.x_axis.x, m.y_axis.y), (2.5, 1.5));
        // A cube: every face equal.
        let m = tiles(Vec3::splat(4.0));
        assert_eq!((m.x_axis.x, m.y_axis.y), (1.0, 1.0));
    }

    #[test]
    fn primitives_are_recognised_only_in_parts() {
        assert_eq!(primitive_shape("parts/block.glb"), Some(PartType::Block));
        assert_eq!(primitive_shape("assets/parts/corner_wedge.glb"), Some(PartType::CornerWedge));
        assert_eq!(primitive_shape("meshes/block.glb"), None);
        assert_eq!(primitive_shape("parts/custom.glb"), None);
    }
}
