//! Build-time auto-discovery of class-schema template folders.
//!
//! Scans `assets/class_schema/<Class>/_instance.toml` (folder-form, matching
//! the on-disk shape of an actual instance under Workspace) and emits a
//! generated Rust file into `OUT_DIR` that declares `BUILTIN_TEMPLATES`
//! as a static slice of `(class_name, included_file_contents)` tuples.
//! `class_schema::templates::BUILTIN_TEMPLATES` just `include!`s that.
//!
//! Result: adding a new class template is a folder drop —
//! `common/assets/class_schema/MyClass/_instance.toml` (plus any sibling
//! resource files the template needs, like asset stubs or child sub-
//! templates). The build system picks it up on the next `cargo check`
//! / `cargo build` automatically and `ClassSchemaRegistry` loads it at
//! runtime.
//!
//! Why folder-form: an instance on disk lives at `Workspace/<Name>/_instance.toml`.
//! The canonical "create instance of class X" operation is then literally
//! `copy_dir_recursive(class_schema/<Class>/, Workspace/<UniqueName>/)`
//! plus a position patch on the root `_instance.toml`. Symmetry between
//! template-on-disk and instance-on-disk eliminates a whole layer of
//! per-class TOML-building code from the spawn paths.
//!
//! `cargo:rerun-if-changed` is emitted for the schema dir + each class
//! folder's `_instance.toml`, so a template edit triggers a minimal
//! rebuild of the `common` crate.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let schema_dir = manifest_dir.join("assets").join("class_schema");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("class_schema_templates.rs");

    // Watch the top-level directory so NEW class folders trigger a
    // rebuild; per-file rerun-if-changed below catches edits inside
    // existing folders.
    println!("cargo:rerun-if-changed={}", schema_dir.display());

    let mut entries: BTreeMap<String, PathBuf> = BTreeMap::new();
    if schema_dir.is_dir() {
        match fs::read_dir(&schema_dir) {
            Ok(read_dir) => {
                for entry in read_dir.flatten() {
                    let path = entry.path();
                    let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
                        continue;
                    };
                    // Only fold class folders, not stray files. Each
                    // class folder must contain `_instance.toml` —
                    // skip anything else (e.g. README, .DS_Store).
                    if !path.is_dir() {
                        continue;
                    }
                    let instance_toml = path.join("_instance.toml");
                    if !instance_toml.is_file() {
                        println!(
                            "cargo:warning=class_schema: skipping {} — no _instance.toml",
                            name,
                        );
                        continue;
                    }
                    println!("cargo:rerun-if-changed={}", instance_toml.display());
                    entries.insert(name.to_string(), instance_toml);
                }
            }
            Err(err) => {
                println!(
                    "cargo:warning=class_schema: failed to read {}: {}",
                    schema_dir.display(),
                    err
                );
            }
        }
    } else {
        println!(
            "cargo:warning=class_schema: directory {} does not exist",
            schema_dir.display()
        );
    }

    // Emit the generated Rust source. `include_str!` resolves the path
    // at compile time from the GENERATED file's own directory, so we
    // write absolute paths. Normalise Windows backslashes to forward
    // slashes so the generated string literal stays valid Rust source.
    let mut out = String::new();
    out.push_str(
        "// @generated by common/build.rs — do not edit.\n\
         // Auto-derived from assets/class_schema/<Class>/_instance.toml.\n\n",
    );
    out.push_str("pub static BUILTIN_TEMPLATES: &[(&str, &str)] = &[\n");
    for (stem, path) in &entries {
        let p = path.display().to_string().replace('\\', "/");
        out.push_str(&format!("    ({:?}, include_str!({:?})),\n", stem, p));
    }
    out.push_str("];\n");

    fs::write(&out_file, out).expect("write generated templates file");
}
