//! Build-time auto-discovery of class-schema template files.
//!
//! Scans `assets/class_schema/*.defaults.toml` and emits a generated
//! Rust file into `OUT_DIR` that declares `BUILTIN_TEMPLATES` as a
//! static slice of `(class_name, included_file_contents)` tuples.
//! `class_schema::templates::BUILTIN_TEMPLATES` just `include!`s that.
//!
//! Result: adding a new class template is a single-file drop —
//! `common/assets/class_schema/MyClass.defaults.toml` and nothing else.
//! The build system picks it up on the next `cargo check` / `cargo
//! build` automatically and `ClassSchemaRegistry` loads it at runtime.
//!
//! `cargo:rerun-if-changed` is emitted for the directory + every
//! individual file, so a template edit triggers a minimal rebuild of
//! the `common` crate.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let schema_dir = manifest_dir.join("assets").join("class_schema");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("class_schema_templates.rs");

    // Tell cargo to rerun if the directory contents change. Explicitly
    // listing individual files would miss NEW files (cargo only rebuilds
    // on paths it was told about); watching the directory itself catches
    // adds and removes, and the per-file lines catch edits.
    println!("cargo:rerun-if-changed={}", schema_dir.display());

    let mut entries: BTreeMap<String, PathBuf> = BTreeMap::new();
    if schema_dir.is_dir() {
        match fs::read_dir(&schema_dir) {
            Ok(read_dir) => {
                for entry in read_dir.flatten() {
                    let path = entry.path();
                    let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
                        continue;
                    };
                    let Some(stem) = name.strip_suffix(".defaults.toml") else {
                        continue;
                    };
                    if stem.is_empty() {
                        continue;
                    }
                    println!("cargo:rerun-if-changed={}", path.display());
                    entries.insert(stem.to_string(), path);
                }
            }
            Err(err) => {
                println!(
                    "cargo:warning=class_schema: failed to read {}: {}",
                    schema_dir.display(),
                    err
                );
            }
        }
    } else {
        println!(
            "cargo:warning=class_schema: directory {} does not exist",
            schema_dir.display()
        );
    }

    // Emit the generated Rust source. `include_str!` resolves the path
    // at compile time from the GENERATED file's own directory, so we
    // write absolute paths. Normalise Windows backslashes to forward
    // slashes so the generated string literal stays valid Rust source.
    let mut out = String::new();
    out.push_str(
        "// @generated by common/build.rs — do not edit.\n\
         // Auto-derived from assets/class_schema/*.defaults.toml.\n\n",
    );
    out.push_str("pub static BUILTIN_TEMPLATES: &[(&str, &str)] = &[\n");
    for (stem, path) in &entries {
        let p = path.display().to_string().replace('\\', "/");
        out.push_str(&format!("    ({:?}, include_str!({:?})),\n", stem, p));
    }
    out.push_str("];\n");

    fs::write(&out_file, out).expect("write generated templates file");
}
