//! Embedded class template registry.
//!
//! `BUILTIN_TEMPLATES` is auto-generated by `common/build.rs`, which
//! scans `assets/class_schema/*.defaults.toml` at compile time and
//! emits a slice of `(class_name, include_str!(...))` tuples into
//! `OUT_DIR`. Adding a new class template is a **single-file drop** —
//! put `MyClass.defaults.toml` in the assets directory and the build
//! picks it up automatically on the next `cargo check`.
//!
//! Hand-editing this file is no longer needed. The generated source
//! lives at `$OUT_DIR/class_schema_templates.rs` if you want to
//! inspect what was baked in.

include!(concat!(env!("OUT_DIR"), "/class_schema_templates.rs"));
