// Copies the Guardian Policy and the moderation playbook from docs/ into
// src/generated/policy_text.mjs so the Worker ships the exact text the docs
// hold. The generated file is committed: a deploy must never depend on a
// build step remembering to run. `--check` exits 1 when the copy has drifted,
// and tests/moderation.test.mjs runs the same comparison.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..', '..', '..', '..');
export const SOURCES = {
  GUARDIAN_POLICY_TEXT: resolve(repo, 'docs', 'architecture', 'AI_GUARDIAN_POLICY_v1.0.md'),
  MODERATION_PLAYBOOK_TEXT: resolve(repo, 'docs', 'moderation', 'PLAYBOOK.md'),
};
export const TARGET = resolve(here, '..', 'src', 'generated', 'policy_text.mjs');

export function render() {
  const lines = [
    '// GENERATED by scripts/sync-policy.mjs from docs/. Do not edit here; edit the',
    '// documents and run `npm run sync-policy`. The moderation tests fail on drift.',
  ];
  for (const [name, path] of Object.entries(SOURCES)) {
    // The repository stores LF; a Windows checkout may hand back CRLF. The
    // anchored policy hash is over the LF form, so normalize before embedding.
    const text = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
    lines.push(`export const ${name} = ${JSON.stringify(text)};`);
  }
  return lines.join('\n') + '\n';
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  const expected = render();
  if (process.argv.includes('--check')) {
    const current = existsSync(TARGET) ? readFileSync(TARGET, 'utf8') : '';
    if (current !== expected) { console.error(`${TARGET} is out of date; run npm run sync-policy`); process.exit(1); }
    console.log('policy text in sync');
  } else {
    writeFileSync(TARGET, expected);
    console.log(`wrote ${TARGET}`);
  }
}
