// =============================================================================
// Eustress Web - Admin Tool Telemetry (/admin/telemetry)
// =============================================================================
// Demand ranking for the engine's discipline-tool surface: which of the
// ~1,400 (mostly aspirational) ribbon tools people actually click, and what
// they say about them. Live counts come from GET /api/telemetry/summary
// (gated server-side by requireAdmin — non-admins see the denied state); the
// mode → discipline → tab → section → button skeleton comes from the static
// /assets/tool_hierarchy.json generated by scripts/gen_web_hierarchy.py, so
// the Worker only ever stores counters keyed by tool id.
//
// The page is built around one job: turn a click into a shipped feature. Every
// row that represents demand carries a Copy button whose payload is a complete,
// self-contained implementation brief (where the button lives, what it promises,
// what users said, which files to touch) — paste it into Claude Code and start.
// =============================================================================

use std::collections::HashMap;

use leptos::prelude::*;
use leptos::task::spawn_local;
use serde::Deserialize;

use crate::api::{ApiClient, ApiError};
use crate::components::{CentralNav, Footer};
use crate::state::AppState;

// -----------------------------------------------------------------------------
// Live summary (mirrors handleTelemetrySummary in infrastructure/cloudflare/api)
// -----------------------------------------------------------------------------

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct ToolCount {
    id: String,
    clicks: i64,
    installs: i64,
    /// Epoch ms of the most recent session that touched this tool (0 = unknown).
    /// Derived server-side from the recent-session feed, not a per-tool counter.
    #[serde(default)]
    last: f64,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct CommentRow {
    ts: f64,
    #[serde(default)]
    tool: String,
    text: String,
    #[serde(default)]
    install: String,
}

/// One engine session's aggregate, newest-first. `#[serde(default)]` throughout
/// so the page keeps working if it deploys ahead of the Worker.
#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct RecentSession {
    #[serde(default)]
    ts: f64,
    #[serde(default)]
    install: String,
    #[serde(default)]
    mode: String,
    #[serde(default)]
    version: String,
    #[serde(default)]
    tools: Vec<(String, i64)>,
    #[serde(default)]
    total: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct DayCount {
    date: String,
    count: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct Summary {
    generated_at: String,
    enabled: bool,
    tools: Vec<ToolCount>,
    comments: Vec<CommentRow>,
    #[serde(default)]
    recent: Vec<RecentSession>,
    sessions_by_day: Vec<DayCount>,
}

// -----------------------------------------------------------------------------
// Static hierarchy (mirrors scripts/gen_web_hierarchy.py output)
// -----------------------------------------------------------------------------

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct HTool {
    id: String,
    label: String,
    tooltip: String,
    wired: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct HSection {
    name: String,
    tools: Vec<HTool>,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct HTab {
    id: String,
    name: String,
    #[serde(default)]
    color: String,
    sections: Vec<HSection>,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct HDiscipline {
    id: String,
    name: String,
    #[serde(default)]
    icon: String,
    tabs: Vec<HTab>,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct HMode {
    id: String,
    name: String,
    #[serde(default)]
    color: String,
    disciplines: Vec<HDiscipline>,
    #[serde(default)]
    tabs: Vec<HTab>,
}

#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
struct Hierarchy {
    modes: Vec<HMode>,
}

#[derive(Clone, Debug, PartialEq)]
enum Load {
    Loading,
    Denied,
    Error(String),
    Ready(Box<(Summary, Hierarchy)>),
}

async fn fetch_hierarchy() -> Result<Hierarchy, String> {
    let resp = gloo_net::http::Request::get("/assets/tool_hierarchy.json")
        .send()
        .await
        .map_err(|e| e.to_string())?;
    resp.json::<Hierarchy>().await.map_err(|e| e.to_string())
}

// -----------------------------------------------------------------------------
// Formatting helpers
// -----------------------------------------------------------------------------

/// 12345 -> "12,345". Tabular numerals plus grouping keeps the stat row scannable.
fn thousands(n: i64) -> String {
    let s = n.abs().to_string();
    let mut out = String::with_capacity(s.len() + s.len() / 3);
    for (i, c) in s.chars().enumerate() {
        if i > 0 && (s.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    if n < 0 {
        format!("-{out}")
    } else {
        out
    }
}

fn now_ms() -> f64 {
    js_sys::Date::now()
}

/// "just now" / "14m ago" / "3h ago" / "2d ago" — absolute dates live in the
/// copied brief, where they survive being pasted somewhere else.
fn rel_time(ts_ms: f64, now: f64) -> String {
    if ts_ms <= 0.0 {
        return String::new();
    }
    let secs = ((now - ts_ms) / 1000.0).max(0.0);
    if secs < 90.0 {
        "just now".to_string()
    } else if secs < 3600.0 {
        format!("{}m ago", (secs / 60.0).round() as i64)
    } else if secs < 86400.0 {
        format!("{}h ago", (secs / 3600.0).round() as i64)
    } else if secs < 86400.0 * 30.0 {
        format!("{}d ago", (secs / 86400.0).round() as i64)
    } else {
        format!("{}mo ago", (secs / (86400.0 * 30.0)).round() as i64)
    }
}

/// UTC date stamp for copied briefs (`2026-07-24 15:03`).
fn stamp(ts_ms: f64) -> String {
    if ts_ms <= 0.0 {
        return "unknown".to_string();
    }
    let d = js_sys::Date::new(&wasm_bindgen::JsValue::from_f64(ts_ms));
    let iso = String::from(d.to_iso_string());
    iso.get(0..16).map(|s| s.replace('T', " ")).unwrap_or(iso)
}

// -----------------------------------------------------------------------------
// Clipboard
// -----------------------------------------------------------------------------

fn copy_text(s: &str) {
    if let Some(win) = web_sys::window() {
        let _ = win.navigator().clipboard().write_text(s);
    }
}

/// Copy button that flashes "Copied" and reverts. `text` is precomputed at
/// render time so the click handler stays synchronous — browsers only honour
/// clipboard writes inside a real user gesture.
#[component]
fn CopyBtn(
    text: String,
    #[prop(optional, into)] label: String,
    #[prop(optional)] strong: bool,
) -> impl IntoView {
    let done = RwSignal::new(false);
    let payload = StoredValue::new(text);
    let idle = if label.is_empty() { "Copy".to_string() } else { label };
    let idle_for_view = idle.clone();
    view! {
        <button
            type="button"
            class="tel-copy"
            class:tel-copy-strong=strong
            class:tel-copy-done=move || done.get()
            title="Copy an implementation brief for this tool — paste straight into Claude Code"
            on:click=move |ev| {
                ev.stop_propagation();
                ev.prevent_default();
                copy_text(&payload.get_value());
                done.set(true);
                spawn_local(async move {
                    gloo_timers::future::TimeoutFuture::new(1500).await;
                    done.set(false);
                });
            }
        >
            {move || if done.get() { "Copied ✓".to_string() } else { idle_for_view.clone() }}
        </button>
    }
}

// -----------------------------------------------------------------------------
// The implementation brief — the whole point of the Copy buttons
// -----------------------------------------------------------------------------

struct BriefInput<'a> {
    id: &'a str,
    label: &'a str,
    tooltip: &'a str,
    wired: bool,
    path: &'a str,
    clicks: i64,
    installs: i64,
    last: f64,
    comments: &'a [CommentRow],
}

fn feature_brief(b: BriefInput<'_>) -> String {
    let mut s = String::new();
    s.push_str(&format!("# Feature request — {} (`{}`)\n\n", b.label, b.id));
    s.push_str(&format!(
        "Lives at      : {}\nIn-app promise: \"{}\"\n",
        if b.path.is_empty() { "(not in the shipped hierarchy)" } else { b.path },
        b.tooltip
    ));
    s.push_str(&format!(
        "Status        : {}\n",
        if b.wired {
            "WIRED — already dispatches; this is a refinement request"
        } else {
            "DREAM — no dispatch arm; clicking shows the \"on the roadmap\" toast"
        }
    ));
    s.push_str(&format!(
        "Demand        : {} click{} from {} install{}{}\n",
        b.clicks,
        if b.clicks == 1 { "" } else { "s" },
        b.installs,
        if b.installs == 1 { "" } else { "s" },
        if b.last > 0.0 {
            format!(" · last seen {}", stamp(b.last))
        } else {
            String::new()
        }
    ));

    if !b.comments.is_empty() {
        s.push_str("\n## What users actually said\n");
        for c in b.comments {
            s.push_str(&format!(
                "- \"{}\"  — install {}, {}\n",
                c.text.trim(),
                if c.install.is_empty() { "anon" } else { &c.install },
                stamp(c.ts)
            ));
        }
    }

    s.push_str("\n## To make it real\n");
    if b.wired {
        s.push_str(&format!(
            "1. Find the `\"{}\"` arm in the `SlintAction::MenuAction` match in\n   \
             eustress/crates/engine/src/ui/slint_ui.rs and extend the behaviour.\n",
            b.id
        ));
    } else {
        s.push_str(&format!(
            "1. Add a `\"{}\"` arm to the `SlintAction::MenuAction` match in\n   \
             eustress/crates/engine/src/ui/slint_ui.rs — the single dispatch choke point.\n\
             2. Add `\"{}\"` to the `WIRED` dict in scripts/gen_tool_metadata.py so the\n   \
             honest-toast path stops treating it as a dream button, then regenerate:\n     \
             python scripts/gen_tool_metadata.py\n     \
             python scripts/gen_tool_icons.py\n     \
             python scripts/gen_web_hierarchy.py\n",
            b.id, b.id
        ));
    }
    s.push_str(
        "3. Keep `cargo test -p eustress-engine --lib -- studio_modes usage_telemetry` green\n   \
         (builtins_fully_populated enforces metadata + a composed icon for every id).\n",
    );
    s
}

// -----------------------------------------------------------------------------
// Small render helpers
// -----------------------------------------------------------------------------

fn count_badge(clicks: i64, installs: i64) -> impl IntoView {
    let hot = installs >= 3 || clicks >= 10;
    view! {
        <span
            class="tel-count"
            class:tel-count-hot=hot
            title=format!("{installs} distinct install(s) · {clicks} click(s)")
        >
            <span class="tel-count-installs">{format!("{installs}⬦")}</span>
            <span class="tel-count-clicks">{format!("{clicks}×")}</span>
        </span>
    }
}

/// Total-only badge for the collapsed mode/discipline/tab rows.
fn total_badge(total: i64) -> impl IntoView {
    view! {
        <span class="tel-count" class:tel-count-zero=total == 0>
            {format!("{}×", thousands(total))}
        </span>
    }
}

fn hay_of_tool(t: &HTool) -> String {
    format!("{} {} {}", t.label, t.id, t.tooltip).to_lowercase()
}

/// Where a tool lives, honestly. Shared ids (`data:import` sits in dozens of
/// disciplines) get every location acknowledged rather than one arbitrary pick,
/// and `prefer` biases the choice toward the mode the click actually came from —
/// otherwise a brief can send you to read the wrong discipline's manifest.
fn path_line(paths: &HashMap<String, Vec<String>>, id: &str, prefer: Option<&str>) -> String {
    let places = match paths.get(id) {
        Some(v) if !v.is_empty() => v,
        _ => return String::new(),
    };
    let chosen = prefer
        .and_then(|p| places.iter().find(|s| s.starts_with(p)))
        .unwrap_or(&places[0]);
    if places.len() > 1 {
        format!(
            "{} (+{} more place{})",
            chosen,
            places.len() - 1,
            if places.len() == 2 { "" } else { "s" }
        )
    } else {
        chosen.clone()
    }
}

// -----------------------------------------------------------------------------
// Page
// -----------------------------------------------------------------------------

#[component]
pub fn AdminTelemetryPage() -> impl IntoView {
    let app_state = expect_context::<AppState>();
    let api_url = app_state.api_url.clone();
    let state = RwSignal::new(Load::Loading);

    // Tree controls.
    let query = RwSignal::new(String::new());
    let active_only = RwSignal::new(false);
    // -1 collapse all · 0 automatic (open where there's demand) · 1 expand all
    let expand = RwSignal::new(0i32);

    Effect::new(move |_| {
        let api_url = api_url.clone();
        spawn_local(async move {
            let client = ApiClient::new(&api_url);
            let summary = client.get::<Summary>("/api/telemetry/summary").await;
            match summary {
                Ok(s) => match fetch_hierarchy().await {
                    Ok(h) => state.set(Load::Ready(Box::new((s, h)))),
                    Err(e) => state.set(Load::Error(format!("hierarchy: {e}"))),
                },
                Err(ApiError::Unauthorized) => state.set(Load::Denied),
                Err(ApiError::Server { status: 403, .. }) => state.set(Load::Denied),
                Err(e) => state.set(Load::Error(e.to_string())),
            }
        });
    });

    let body = move || match state.get() {
        Load::Loading => view! {
            <div class="loading-state">
                <div class="spinner"></div>
                <p class="loading-message">"Loading tool telemetry…"</p>
            </div>
        }
        .into_any(),

        Load::Denied => view! {
            <div class="admin-denied">
                <h2>"Admin access required"</h2>
                <p>"This dashboard is restricted to the Eustress admin. Sign in with the admin identity to continue."</p>
                <a class="btn-primary" href="/login">"Sign in"</a>
            </div>
        }
        .into_any(),

        Load::Error(msg) => view! {
            <div class="alert alert-error admin-alert">
                <strong>"Couldn't load telemetry. "</strong>
                <span>{msg}</span>
            </div>
        }
        .into_any(),

        Load::Ready(data) => {
            let (s, h) = *data;
            let now = now_ms();

            // ---- indexes -------------------------------------------------
            let counts: HashMap<String, (i64, i64, f64)> = s
                .tools
                .iter()
                .map(|t| (t.id.clone(), (t.clicks, t.installs, t.last)))
                .collect();

            // Where each tool lives, for briefs and the demand list. A tool id
            // can appear in several disciplines; first occurrence wins.
            let mut paths: HashMap<String, Vec<String>> = HashMap::new();
            let mut metas: HashMap<String, (String, String, bool)> = HashMap::new();
            let mode_names: HashMap<String, String> =
                h.modes.iter().map(|m| (m.id.clone(), m.name.clone())).collect();
            {
                let mut note = |path: String, t: &HTool| {
                    paths.entry(t.id.clone()).or_default().push(path);
                    metas
                        .entry(t.id.clone())
                        .or_insert_with(|| (t.label.clone(), t.tooltip.clone(), t.wired));
                };
                for m in &h.modes {
                    if m.disciplines.is_empty() {
                        for tab in &m.tabs {
                            for sec in &tab.sections {
                                for t in &sec.tools {
                                    note(
                                        format!("{} ▸ {} ▸ {}", m.name, tab.name, sec.name),
                                        t,
                                    );
                                }
                            }
                        }
                    } else {
                        for d in &m.disciplines {
                            for tab in &d.tabs {
                                for sec in &tab.sections {
                                    for t in &sec.tools {
                                        note(
                                            format!(
                                                "{} ▸ {} ▸ {} ▸ {}",
                                                m.name, d.name, tab.name, sec.name
                                            ),
                                            t,
                                        );
                                    }
                                }
                            }
                        }
                    }
                }
            }

            let mut comments_by_tool: HashMap<String, Vec<CommentRow>> = HashMap::new();
            for c in &s.comments {
                if !c.tool.is_empty() {
                    comments_by_tool.entry(c.tool.clone()).or_default().push(c.clone());
                }
            }

            // Brief for a tool id, pulling everything known about it together.
            let brief_for = {
                let paths = paths.clone();
                let metas = metas.clone();
                let counts = counts.clone();
                let comments_by_tool = comments_by_tool.clone();
                move |id: &str| -> String {
                    let empty_meta = (id.to_string(), String::new(), false);
                    let (label, tooltip, wired) = metas.get(id).cloned().unwrap_or(empty_meta);
                    let (clicks, installs, last) = counts.get(id).copied().unwrap_or((0, 0, 0.0));
                    let no_comments: Vec<CommentRow> = Vec::new();
                    let cmts = comments_by_tool.get(id).unwrap_or(&no_comments);
                    let path = path_line(&paths, id, None);
                    feature_brief(BriefInput {
                        id,
                        label: &label,
                        tooltip: &tooltip,
                        wired,
                        path: &path,
                        clicks,
                        installs,
                        last,
                        comments: cmts,
                    })
                }
            };

            // ---- headline numbers ----------------------------------------
            let total_clicks: i64 = s.tools.iter().map(|t| t.clicks).sum();
            let dream_clicks: i64 = s
                .tools
                .iter()
                .filter(|t| !metas.get(&t.id).map(|m| m.2).unwrap_or(false))
                .map(|t| t.clicks)
                .sum();
            let sessions_14d: i64 = s.sessions_by_day.iter().map(|d| d.count).sum();
            let comment_count = s.comments.len();

            // ---- sessions sparkline (14 days) ----------------------------
            let peak = s.sessions_by_day.iter().map(|d| d.count).max().unwrap_or(0).max(1);
            let bars = s
                .sessions_by_day
                .iter()
                .map(|d| {
                    let pct = (d.count as f64 / peak as f64 * 100.0).max(if d.count > 0 { 6.0 } else { 2.0 });
                    view! {
                        <div class="admin-bar" title=format!("{} — {} session(s)", d.date, d.count)>
                            <div
                                class="admin-bar-fill"
                                class:tel-bar-empty=d.count == 0
                                style=format!("height:{pct:.1}%")
                            ></div>
                        </div>
                    }
                })
                .collect_view();
            let first_day = s.sessions_by_day.first().map(|d| d.date.clone()).unwrap_or_default();
            let last_day = s.sessions_by_day.last().map(|d| d.date.clone()).unwrap_or_default();

            // ---- recent feed (comments + sessions, newest first) ----------
            enum Feed {
                Comment(CommentRow),
                Session(RecentSession),
            }
            let mut feed: Vec<(f64, Feed)> = Vec::new();
            for c in &s.comments {
                feed.push((c.ts, Feed::Comment(c.clone())));
            }
            for r in &s.recent {
                feed.push((r.ts, Feed::Session(r.clone())));
            }
            feed.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
            feed.truncate(40);

            let feed_empty = feed.is_empty();

            // "Copy all" — one paste that briefs an entire work session.
            let copy_all = {
                let mut out = String::from(
                    "# Eustress alpha — recent tool demand\n\nPasted from /admin/telemetry. Each block is a self-contained request.\n\n",
                );
                for (_, item) in feed.iter().take(15) {
                    match item {
                        Feed::Comment(c) => {
                            if c.tool.is_empty() {
                                out.push_str(&format!(
                                    "---\n\n# General feedback ({})\n\n\"{}\"\n\n",
                                    stamp(c.ts),
                                    c.text.trim()
                                ));
                            } else {
                                out.push_str("---\n\n");
                                out.push_str(&brief_for(&c.tool));
                                out.push('\n');
                            }
                        }
                        Feed::Session(r) => {
                            out.push_str(&format!(
                                "---\n\n# Session {} — mode {}, {} click(s)\n",
                                stamp(r.ts),
                                if r.mode.is_empty() { "?" } else { &r.mode },
                                r.total
                            ));
                            let prefer = mode_names.get(&r.mode).map(|s| s.as_str());
                            for (id, n) in r.tools.iter().take(8) {
                                let p = path_line(&paths, id, prefer);
                                out.push_str(&format!(
                                    "  - {} ×{}  ({})\n",
                                    id,
                                    n,
                                    if p.is_empty() { "—".to_string() } else { p }
                                ));
                            }
                            out.push('\n');
                        }
                    }
                }
                out
            };

            let feed_rows = feed
                .into_iter()
                .map(|(ts, item)| match item {
                    Feed::Comment(c) => {
                        let tool_label = if c.tool.is_empty() {
                            "General feedback".to_string()
                        } else {
                            metas
                                .get(&c.tool)
                                .map(|m| m.0.clone())
                                .unwrap_or_else(|| c.tool.clone())
                        };
                        let path = path_line(&paths, &c.tool, None);
                        let copy = if c.tool.is_empty() {
                            format!(
                                "# General feedback ({})\n\n\"{}\"\n\n(install {})\n",
                                stamp(ts),
                                c.text.trim(),
                                c.install
                            )
                        } else {
                            brief_for(&c.tool)
                        };
                        view! {
                            <article class="tel-feed-item tel-feed-comment">
                                <div class="tel-feed-head">
                                    <span class="tel-feed-kind tel-feed-kind-said">"SAID"</span>
                                    <span class="tel-feed-title">{tool_label}</span>
                                    <span class="tel-feed-time">{rel_time(ts, now)}</span>
                                    <CopyBtn text=copy strong=true />
                                </div>
                                <blockquote class="tel-feed-quote">{c.text.clone()}</blockquote>
                                <div class="tel-feed-sub">
                                    {(!path.is_empty()).then(|| view! { <span class="tel-path">{path}</span> })}
                                    <code class="tel-tool-id">{c.install.clone()}</code>
                                </div>
                            </article>
                        }
                        .into_any()
                    }
                    Feed::Session(r) => {
                        let chips = r
                            .tools
                            .iter()
                            .take(6)
                            .map(|(id, n)| {
                                let label = metas
                                    .get(id)
                                    .map(|m| m.0.clone())
                                    .unwrap_or_else(|| id.clone());
                                let brief = brief_for(id);
                                view! {
                                    <button
                                        type="button"
                                        class="tel-tool-chip"
                                        title=format!("{id} — click to copy its implementation brief")
                                        on:click=move |ev| {
                                            ev.prevent_default();
                                            copy_text(&brief);
                                        }
                                    >
                                        <span>{label}</span>
                                        <span class="tel-tool-chip-n">{format!("×{n}")}</span>
                                    </button>
                                }
                            })
                            .collect_view();
                        let more = r.tools.len().saturating_sub(6);
                        let session_copy = {
                            let mut out = format!(
                                "# Session {} — mode {}, {} click(s), engine {}\n\n",
                                stamp(ts),
                                if r.mode.is_empty() { "?" } else { &r.mode },
                                r.total,
                                if r.version.is_empty() { "?" } else { &r.version }
                            );
                            let prefer = mode_names.get(&r.mode).map(|x| x.as_str());
                            for (id, n) in r.tools.iter() {
                                let p = path_line(&paths, id, prefer);
                                out.push_str(&format!(
                                    "  - {} ×{}  ({})\n",
                                    id,
                                    n,
                                    if p.is_empty() { "—".to_string() } else { p }
                                ));
                            }
                            out.push_str("\nFull briefs: open /admin/telemetry and copy per tool.\n");
                            out
                        };
                        view! {
                            <article class="tel-feed-item">
                                <div class="tel-feed-head">
                                    <span class="tel-feed-kind tel-feed-kind-used">"USED"</span>
                                    <span class="tel-feed-title">
                                        {if r.mode.is_empty() { "Session".to_string() } else { r.mode.clone() }}
                                        <span class="tel-feed-count">{format!(" · {} clicks", r.total)}</span>
                                    </span>
                                    <span class="tel-feed-time">{rel_time(ts, now)}</span>
                                    <CopyBtn text=session_copy />
                                </div>
                                <div class="tel-chips">
                                    {chips}
                                    {(more > 0).then(|| view! { <span class="tel-more">{format!("+{more} more")}</span> })}
                                </div>
                            </article>
                        }
                        .into_any()
                    }
                })
                .collect_view();

            // ---- wiring queue --------------------------------------------
            let top_rows = s
                .tools
                .iter()
                .take(12)
                .enumerate()
                .map(|(i, t)| {
                    let label = metas.get(&t.id).map(|m| m.0.clone()).unwrap_or_else(|| t.id.clone());
                    let path = path_line(&paths, &t.id, None);
                    let wired = metas.get(&t.id).map(|m| m.2).unwrap_or(false);
                    let width = (t.clicks as f64 / s.tools.first().map(|x| x.clicks.max(1)).unwrap_or(1) as f64
                        * 100.0)
                        .clamp(3.0, 100.0);
                    let brief = brief_for(&t.id);
                    view! {
                        <div class="tel-q-row">
                            <span class="tel-q-rank">{format!("{}", i + 1)}</span>
                            <div class="tel-q-main">
                                <div class="tel-q-line">
                                    <span class="tel-q-label">{label}</span>
                                    <span
                                        class="tel-chip"
                                        class:tel-chip-wired=wired
                                        class:tel-chip-dream=!wired
                                    >
                                        {if wired { "WIRED" } else { "DREAM" }}
                                    </span>
                                    {count_badge(t.clicks, t.installs)}
                                </div>
                                <div class="tel-q-meter">
                                    <div class="tel-q-meter-fill" style=format!("width:{width:.1}%")></div>
                                </div>
                                <div class="tel-q-path">{path}</div>
                            </div>
                            <CopyBtn text=brief />
                        </div>
                    }
                })
                .collect_view();

            // ---- full surface tree ---------------------------------------
            // Filtering is per-node reactive (fine-grained: a keystroke toggles
            // classes, it does not re-render ~1,400 rows).
            let modes = h
                .modes
                .iter()
                .map(|m| {
                    let mut mode_hay = m.name.to_lowercase();
                    let mut mode_total = 0i64;

                    let inner = if m.disciplines.is_empty() {
                        let (v, hay, total) =
                            tabs_view(&m.tabs, &counts, &comments_by_tool, &brief_for, now, query, active_only, expand);
                        mode_hay.push(' ');
                        mode_hay.push_str(&hay);
                        mode_total += total;
                        v.into_any()
                    } else {
                        let mut discs = Vec::new();
                        for d in &m.disciplines {
                            let (tabs, hay, total) = tabs_view(
                                &d.tabs,
                                &counts,
                                &comments_by_tool,
                                &brief_for,
                                now,
                                query,
                                active_only,
                                expand,
                            );
                            let disc_hay = format!("{} {}", d.name.to_lowercase(), hay);
                            mode_hay.push(' ');
                            mode_hay.push_str(&disc_hay);
                            mode_total += total;

                            let hay_v = disc_hay.clone();
                            let visible = move || node_visible(&hay_v, total, query, active_only);
                            let hay_o = disc_hay.clone();
                            let open = move || node_open(&hay_o, total, query, expand);
                            discs.push(view! {
                                <details class="tel-node tel-discipline" class:tel-hidden=move || !visible() prop:open=open>
                                    <summary>
                                        <span class="tel-caret"></span>
                                        <span class="tel-disc-name">{d.name.clone()}</span>
                                        {total_badge(total)}
                                    </summary>
                                    <div class="tel-children">{tabs}</div>
                                </details>
                            });
                        }
                        discs.into_iter().collect_view().into_any()
                    };

                    let accent = if m.color.is_empty() { "#8b949e".to_string() } else { m.color.clone() };
                    let hay_v = mode_hay.clone();
                    let visible = move || node_visible(&hay_v, mode_total, query, active_only);
                    let hay_o = mode_hay.clone();
                    let open = move || node_open(&hay_o, mode_total, query, expand);
                    let disc_note = if m.disciplines.is_empty() {
                        format!("{} tabs", m.tabs.len())
                    } else {
                        format!("{} disciplines", m.disciplines.len())
                    };
                    view! {
                        <details
                            class="tel-node tel-mode"
                            class:tel-hidden=move || !visible()
                            prop:open=open
                            style=format!("--tel-accent:{accent}")
                        >
                            <summary>
                                <span class="tel-caret"></span>
                                <span class="tel-mode-dot"></span>
                                <span class="tel-mode-name">{m.name.clone()}</span>
                                <span class="tel-node-note">{disc_note}</span>
                                {total_badge(mode_total)}
                            </summary>
                            <div class="tel-children">{inner}</div>
                        </details>
                    }
                })
                .collect_view();

            let generated = s.generated_at.clone();

            view! {
                <div class="admin-wrap">
                    <section class="admin-headline tel-headline">
                        <div class="admin-hero-card admin-hero-primary">
                            <span class="admin-hero-value">{thousands(total_clicks)}</span>
                            <span class="admin-hero-label">"Tool clicks (all time)"</span>
                        </div>
                        <div class="admin-hero-card">
                            <span class="admin-hero-value">{thousands(dream_clicks)}</span>
                            <span class="admin-hero-label">"Dream-button votes"</span>
                        </div>
                        <div class="admin-hero-card">
                            <span class="admin-hero-value">{thousands(s.tools.len() as i64)}</span>
                            <span class="admin-hero-label">"Distinct tools touched"</span>
                        </div>
                        <div class="admin-hero-card">
                            <span class="admin-hero-value">{thousands(sessions_14d)}</span>
                            <span class="admin-hero-label">"Sessions (14 days)"</span>
                        </div>
                        <div class="admin-hero-card">
                            <span class="admin-hero-value">{thousands(comment_count as i64)}</span>
                            <span class="admin-hero-label">"Written requests"</span>
                        </div>
                    </section>

                    <section class="tel-split">
                        <div class="dashboard-section tel-panel">
                            <div class="section-header-industrial tel-panel-head">
                                <h2>"Recent requests"</h2>
                                <CopyBtn text=copy_all label="Copy top 15" strong=true />
                            </div>
                            <p class="tel-panel-sub">
                                "Newest first. Every Copy button yields a complete implementation brief — where the button lives, what it promises, what users said, and which files to touch."
                            </p>
                            <div class="tel-feed">
                                {if feed_empty {
                                    view! {
                                        <p class="tel-empty">
                                            "Nothing yet. Clicks arrive when a tester quits the engine; written requests arrive via Help ▸ Send Feedback."
                                        </p>
                                    }
                                        .into_any()
                                } else {
                                    feed_rows.into_any()
                                }}
                            </div>
                        </div>

                        <div class="tel-side">
                            <div class="dashboard-section tel-panel">
                                <div class="section-header-industrial"><h2>"Sessions"</h2></div>
                                <div class="admin-bars tel-bars">{bars}</div>
                                <div class="tel-axis">
                                    <span>{first_day}</span>
                                    <span class="tel-axis-peak">{format!("peak {peak}")}</span>
                                    <span>{last_day}</span>
                                </div>
                            </div>

                            <div class="dashboard-section tel-panel">
                                <div class="section-header-industrial"><h2>"Wiring queue"</h2></div>
                                <p class="tel-panel-sub">"Ranked by distinct installs, then clicks — build down this list."</p>
                                <div class="tel-queue">{top_rows}</div>
                            </div>
                        </div>
                    </section>

                    <section class="dashboard-section tel-panel">
                        <div class="section-header-industrial tel-panel-head">
                            <h2>"Full surface"</h2>
                            <span class="tel-breadcrumb">"mode ▸ discipline ▸ tab ▸ section ▸ button"</span>
                        </div>
                        <div class="tel-controls">
                            <input
                                class="tel-search"
                                type="search"
                                placeholder="Filter by tool, id, tooltip, section…"
                                prop:value=move || query.get()
                                on:input=move |ev| query.set(event_target_value(&ev))
                            />
                            <label class="tel-toggle">
                                <input
                                    type="checkbox"
                                    prop:checked=move || active_only.get()
                                    on:change=move |ev| active_only.set(event_target_checked(&ev))
                                />
                                <span>"Only tools with activity"</span>
                            </label>
                            <div class="tel-btn-row">
                                <button type="button" class="tel-ghost" on:click=move |_| expand.set(1)>"Expand all"</button>
                                <button type="button" class="tel-ghost" on:click=move |_| expand.set(-1)>"Collapse all"</button>
                                <button type="button" class="tel-ghost" on:click=move |_| expand.set(0)>"Auto"</button>
                            </div>
                        </div>
                        <div class="tel-tree">{modes}</div>
                    </section>

                    <p class="admin-generated">"Generated " {generated}</p>
                </div>
            }
            .into_any()
        }
    };

    view! {
        <div class="page page-admin page-admin-telemetry">
            <CentralNav active="admin".to_string() />
            <section class="dashboard-hero">
                <div class="hero-header">
                    <div class="header-line"></div>
                    <span class="header-tag">"ADMIN"</span>
                    <div class="header-line"></div>
                </div>
                <h1 class="dashboard-title">"Tool Telemetry"</h1>
                <p class="dashboard-subtitle">
                    "Anonymous demand for the discipline surface. ⬦ distinct installs · × clicks. "
                    <a href="/admin">"← funnel dashboard"</a>
                </p>
            </section>

            <div class="dashboard-container">{body}</div>
            <Footer />
        </div>
    }
}

// -----------------------------------------------------------------------------
// Tree node predicates — shared by every level so filtering behaves uniformly
// -----------------------------------------------------------------------------

fn node_visible(hay: &str, total: i64, query: RwSignal<String>, active_only: RwSignal<bool>) -> bool {
    let q = query.get();
    let q = q.trim().to_lowercase();
    (q.is_empty() || hay.contains(&q)) && (!active_only.get() || total > 0)
}

fn node_open(hay: &str, total: i64, query: RwSignal<String>, expand: RwSignal<i32>) -> bool {
    match expand.get() {
        1 => true,
        -1 => false,
        _ => {
            let q = query.get();
            let q = q.trim().to_lowercase();
            if !q.is_empty() {
                hay.contains(&q)
            } else {
                total > 0
            }
        }
    }
}

/// Renders a tab list, returning (view, search haystack, total clicks) so the
/// parent can build its own haystack/total without walking the tree twice.
#[allow(clippy::too_many_arguments)]
fn tabs_view(
    tabs: &[HTab],
    counts: &HashMap<String, (i64, i64, f64)>,
    comments_by_tool: &HashMap<String, Vec<CommentRow>>,
    brief_for: &impl Fn(&str) -> String,
    now: f64,
    query: RwSignal<String>,
    active_only: RwSignal<bool>,
    expand: RwSignal<i32>,
) -> (impl IntoView, String, i64) {
    let mut all_hay = String::new();
    let mut all_total = 0i64;
    let mut views = Vec::new();

    for tab in tabs {
        let mut tab_hay = tab.name.to_lowercase();
        let mut tab_total = 0i64;
        let mut sections = Vec::new();

        for sec in &tab.sections {
            let mut sec_hay = sec.name.to_lowercase();
            let mut sec_total = 0i64;
            let mut tools = Vec::new();

            for t in &sec.tools {
                let (clicks, installs, last) = counts.get(&t.id).copied().unwrap_or((0, 0, 0.0));
                sec_total += clicks;
                let hay = hay_of_tool(t);
                sec_hay.push(' ');
                sec_hay.push_str(&hay);

                let cmts = comments_by_tool.get(&t.id).cloned().unwrap_or_default();
                let has_activity = clicks > 0 || !cmts.is_empty();
                let hay_v = hay.clone();
                let visible = move || {
                    let q = query.get();
                    let q = q.trim().to_lowercase();
                    (q.is_empty() || hay_v.contains(&q)) && (!active_only.get() || has_activity)
                };

                let comment_block = (!cmts.is_empty()).then(|| {
                    cmts.iter()
                        .map(|c| {
                            view! {
                                <div class="tel-tool-comment">
                                    <span class="tel-quote-mark">"“"</span>
                                    <span class="tel-quote-text">{c.text.clone()}</span>
                                    <span class="tel-quote-meta">
                                        {format!("{} · {}", c.install.clone(), rel_time(c.ts, now))}
                                    </span>
                                </div>
                            }
                        })
                        .collect_view()
                });
                let comment_badge = (!cmts.is_empty()).then(|| {
                    let n = cmts.len();
                    view! {
                        <span class="tel-cmt-badge" title=format!("{n} written request(s) about this button")>
                            {format!("💬 {n}")}
                        </span>
                    }
                });
                let last_seen = (last > 0.0).then(|| {
                    view! { <span class="tel-last">{rel_time(last, now)}</span> }
                });

                let wired = t.wired;
                tools.push(view! {
                    <div
                        class="tel-tool"
                        class:tel-tool-zero=!has_activity
                        class:tel-tool-said=!cmts.is_empty()
                        class:tel-hidden=move || !visible()
                    >
                        <div class="tel-tool-line">
                            <span
                                class="tel-chip"
                                class:tel-chip-wired=wired
                                class:tel-chip-dream=!wired
                            >
                                {if wired { "WIRED" } else { "DREAM" }}
                            </span>
                            <span class="tel-tool-label" title=t.tooltip.clone()>
                                {t.label.clone()}
                            </span>
                            <code class="tel-tool-id">{t.id.clone()}</code>
                            {comment_badge}
                            {last_seen}
                            {count_badge(clicks, installs)}
                            <CopyBtn text=brief_for(&t.id) />
                        </div>
                        {comment_block}
                    </div>
                });
            }

            tab_total += sec_total;
            tab_hay.push(' ');
            tab_hay.push_str(&sec_hay);

            let hay_v = sec_hay.clone();
            let visible = move || node_visible(&hay_v, sec_total, query, active_only);
            sections.push(view! {
                <div class="tel-section" class:tel-hidden=move || !visible()>
                    <div class="tel-section-name">
                        <span>{sec.name.clone()}</span>
                        {(sec_total > 0).then(|| view! { <span class="tel-section-count">{format!("{sec_total}×")}</span> })}
                    </div>
                    <div class="tel-tools">{tools}</div>
                </div>
            });
        }

        all_total += tab_total;
        all_hay.push(' ');
        all_hay.push_str(&tab_hay);

        let hay_v = tab_hay.clone();
        let visible = move || node_visible(&hay_v, tab_total, query, active_only);
        let hay_o = tab_hay.clone();
        let open = move || node_open(&hay_o, tab_total, query, expand);
        let color = if tab.color.is_empty() { "#8b949e".to_string() } else { tab.color.clone() };
        views.push(view! {
            <details
                class="tel-node tel-tab"
                class:tel-hidden=move || !visible()
                prop:open=open
                style=format!("--tel-tab-color:{color}")
            >
                <summary>
                    <span class="tel-caret"></span>
                    <span class="tel-tab-name">{tab.name.clone()}</span>
                    {total_badge(tab_total)}
                </summary>
                <div class="tel-children">{sections}</div>
            </details>
        });
    }

    (views.into_iter().collect_view(), all_hay, all_total)
}
